#!/bin/bash
echo "=== Build Validation ==="
echo ""
echo "1. Checking React version in bundle..."
grep -o "react@[0-9.]*" node_modules/react/package.json || echo "Could not determine React version"
echo ""
echo "2. Checking if index.html exists..."
ls -lh out/index.html || echo "ERROR: index.html not found"
echo ""
echo "3. Checking index.html size..."
du -h out/index.html || echo "ERROR: Cannot check size"
echo ""
echo "4. Checking for Turbopack references..."
grep -i "turbopack" out/index.html && echo "WARNING: Turbopack found!" || echo "✓ No Turbopack"
echo ""
echo "5. Checking for React 19 references..."
grep "react.*19" out/_next/static/chunks/*.js 2>/dev/null | wc -l
echo ""
echo "6. Checking JavaScript chunks..."
ls -lh out/_next/static/chunks/ | head -10
echo ""
echo "7. Sample of index.html content..."
head -50 out/index.html | grep -o "Maxim AI" | head -1 || echo "ERROR: Content not found"
